### ISSUE TITLE
Investigate other ways to detect node-engine

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-execute#138]
## What happened?

* What were you attempting to do?

Trying to `pack build` a dotnet-core fixture that uses node: https://github.com/paketo-buildpacks/dotnet-publish/tree/v0.1.3/integration/testdata/source_prerender_node

This app requires node to run, and works in V2Bs, but doesn't *just work* in v3 buildpacks because the `csproj` file doesn't explicitly contain a `<Targets>` section with node.

To get this app to build, we added the `<Targets>` section, or requiring the build plan buildpack. 

It seems like currently the buildpack checks if node is used at build-time, and then assumes it's needed at run-time as well. We should investigate if there is a better way to detect node is needed at runtime other than explicitly checking just the csproj file so we can avoid forcing users to pull in the build-plan buildpack.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [X] I have included steps for reproduction.

**Comment by fg-j** [comment]
The provided app relies on a .NET Core 2.1 feature (frontend prerendering) that was removed in .NET Core v0.3.1. Since the .NET buildpack [no longer supports .NET 2.1](https://github.com/paketo-buildpacks/dotnet-core/releases#:~:text=Dependencies%3A,280459701eee9f7d9cfea740d45978556fa46753bfc7b858b7c83014ae209083), I'll close this issue for now. It can be reopened if we identify a supported app that the buildpack fails to build because of an unmet node requirement.
