### ISSUE TITLE
Investigate: SBOM for node_modules

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-execute#320]
In https://github.com/paketo-buildpacks/dotnet-execute/pull/318, the prospect of supporting SBOM entries for apps with `node_modules` was discussed.  As it stands, the current SBOM generation implementation does not produce any entries for `node_modules` even if they are left on the final app image.

We should determine if this is a worthwhile use case to support. A related bonus in this investigation is to figure out if `node_modules` are needed on the final app image at all, and determining if we can implement some image trimming to remove them.

**Comment by fg-j** [comment]
Syft can generate SBOMs for node components by scanning `node_modules` directories. So, if `node_modules` are present in an app, we can produce a SBOM of the modules with our existing tooling.

Some .NET apps that use JavaScript components won't have `node_modules` before they are built with `dotnet publish`. For example, this [test fixture app](https://github.com/paketo-buildpacks/dotnet-core/blob/0d9e8973ba4eb010ab4ad3d33f426115aa449789/integration/testdata/source-app) includes a JavaScript frontend called `ClientApp`. The checked-in version of the frontend does not have `node_modules`, but it does have a `package.json` and `package-lock.json`. Thanks to [configuration in the app's project file](https://github.com/paketo-buildpacks/dotnet-core/blob/main/integration/testdata/source-app/source-app.csproj#L44-L45), the `node_modules` get installed as part of `dotnet publish`. `node_modules` is present in the build container after `dotnet publish` runs. 

Since the buildpack for .NET Publish [removes the contents of the working directory](https://github.com/paketo-buildpacks/dotnet-publish/blob/262955b57b6c16ecf02e43123f84ce8ca62d5f67/build.go#L158), scanning the `node_modules` would have to happen during the build phase of the buildpack for .NET publish.

To get a valuable SBOM, the buildpack would need to determine _which directory_ to scan for node modules. In the sample app used above, the root of the frontend app is [stored in a user-defined property](https://github.com/paketo-buildpacks/dotnet-core/blob/0d9e8973ba4eb010ab4ad3d33f426115aa449789/integration/testdata/source-app/source-app.csproj#L7). The property is referenced later in the file to [set the working directory](https://github.com/paketo-buildpacks/dotnet-core/blob/0d9e8973ba4eb010ab4ad3d33f426115aa449789/integration/testdata/source-app/source-app.csproj#L44) for running NPM commands. Since the `SpaRoot` is a user-defined property, the buildpack cannot rely on this property to find the frontend component.

I will continue investigating how the buildpack can discover the correct `node_modules` directory.

**Comment by fg-j** [comment]
>  A related bonus in this investigation is to figure out if node_modules are needed on the final app image at all, and determining if we can implement some image trimming to remove them.
As far as I can tell, `node_modules` are currently not included in the final app image. They are removed when source code is removed by the buildpack for .NET publish. There's nothing to trim.

**Comment by fg-j** [comment]
Since the structure of a .NET project with JavaScript frontend components can vary significantly, perhaps the simplest approach is to search the working directory (and its children) for directories called `node_modules` after `dotnet publish`. Once a node modules directory is found, scan it and attach the SBOM to a layer associated with the  dotnet-publish buildpack.
